packages:
  - examples/*
  - vanity-h

catalog:
  '@types/node': ^25.6.0
  '@types/react': ^19.2.14
  preact: ^10.29.1
  react: ^19.2.5
  typescript: ^6.0.2
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.18
  vite-plus: ^0.1.18
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vue: ^3.5.32

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
